### ISSUE TITLE
Documentation is misleading?

### ISSUE THREAD

**Issue by sneakyness** [MorganCaron/IsometricSass#4]
I've never used Sass before. 

Your first example has `@import isometric` in the sass file, and two divs in the html. I've tried this (yes I'm compiling the sass) and it doesn't seem to work. What am I missing? 

Cheers

**Comment by sneakyness** [comment]
Sass:
```
@import isometric

$size: 1rem

.container
	display: block
	height: $size*10

.grid
	+grid($size, #7CCECB)
	width: $size*5
	height: $size*5
```

Html:
```
  <div class="container">
    <div class="isometric-container">
      <div class="isometric">
        Ass
        <div class="grid">Piss</div>
      </div>
    </div>
  </div>
```

Result: 
![](https://i.imgur.com/mIWGvrd.png)

Where's the grid??

**Comment by MorganCaron** [comment]
Hi sneakness,

I tested your code on jsfiddle, and I get the same result as you:
https://jsfiddle.net/rqgk7wvx/1/
(I couldn't find how to import a Sass file to jsfiddle.js, so I copied it at the beginning of the code. Your code is at the end of the Sass file)

The grid starts to be visible when $size exceeds 4rem:
https://jsfiddle.net/rqgk7wvx/2/
It is indeed a problem. The problem is that the grid lines are too small to be visible.

I solved the problem by adding a lineweight parameter to the grid.
=grid($size, $lineweight, $color) 

Examples:
https://jsfiddle.net/5srdLken/
grid size: 5rem
lineweight: 1%

https://jsfiddle.net/5srdLken/1/
grid size: 5rem
lineweight: 5%

https://jsfiddle.net/5srdLken/2/
grid size: 1rem
lineweight: 5%

Does that solve your problem ?
Feel free to request again if necessary

**Comment by sneakyness** [comment]
Thank you! Yes it does
